using System;

namespace Khronos;

#pragma warning disable IDE1006 // Naming Styles

internal static unsafe class OpenGL
{
    public delegate nint FunctionLoader(string name);

    public static void glInitialize(FunctionLoader functionLoader)
    {
        static nint LoadRequiredFunction(FunctionLoader functionLoader, string name)
        {
            nint value = functionLoader(name);
            if (value == 0)
            {
                throw new Exception($"Could not load required opengl function '{name}'");
            }
            return value;
        }
        
        static nint LoadOptionalFunction(FunctionLoader functionLoader, string name)
        {
            nint value = functionLoader(name);
            return value;
        }
        pfn_glActiveTexture = LoadRequiredFunction(functionLoader, "glActiveTexture");
        pfn_glAttachShader = LoadRequiredFunction(functionLoader, "glAttachShader");
        pfn_glBindBuffer = LoadRequiredFunction(functionLoader, "glBindBuffer");
        pfn_glBindFramebuffer = LoadRequiredFunction(functionLoader, "glBindFramebuffer");
        pfn_glBindTexture = LoadRequiredFunction(functionLoader, "glBindTexture");
        pfn_glBlendFunc = LoadRequiredFunction(functionLoader, "glBlendFunc");
        pfn_glBufferData = LoadRequiredFunction(functionLoader, "glBufferData");
        pfn_glBufferSubData = LoadRequiredFunction(functionLoader, "glBufferSubData");
        pfn_glCheckFramebufferStatus = LoadRequiredFunction(functionLoader, "glCheckFramebufferStatus");
        pfn_glClear = LoadRequiredFunction(functionLoader, "glClear");
        pfn_glClearColor = LoadRequiredFunction(functionLoader, "glClearColor");
        pfn_glClearDepthf = LoadRequiredFunction(functionLoader, "glClearDepthf");
        pfn_glClearStencil = LoadRequiredFunction(functionLoader, "glClearStencil");
        pfn_glCompileShader = LoadRequiredFunction(functionLoader, "glCompileShader");
        pfn_glCreateProgram = LoadRequiredFunction(functionLoader, "glCreateProgram");
        pfn_glCreateShader = LoadRequiredFunction(functionLoader, "glCreateShader");
        pfn_glCullFace = LoadRequiredFunction(functionLoader, "glCullFace");
        pfn_glDeleteBuffers = LoadRequiredFunction(functionLoader, "glDeleteBuffers");
        pfn_glDeleteFramebuffers = LoadRequiredFunction(functionLoader, "glDeleteFramebuffers");
        pfn_glDeleteShader = LoadRequiredFunction(functionLoader, "glDeleteShader");
        pfn_glDeleteTextures = LoadRequiredFunction(functionLoader, "glDeleteTextures");
        pfn_glDepthFunc = LoadRequiredFunction(functionLoader, "glDepthFunc");
        pfn_glDepthMask = LoadRequiredFunction(functionLoader, "glDepthMask");
        pfn_glDisable = LoadRequiredFunction(functionLoader, "glDisable");
        pfn_glDrawArrays = LoadRequiredFunction(functionLoader, "glDrawArrays");
        pfn_glDrawElements = LoadRequiredFunction(functionLoader, "glDrawElements");
        pfn_glEnable = LoadRequiredFunction(functionLoader, "glEnable");
        pfn_glEnableVertexAttribArray = LoadRequiredFunction(functionLoader, "glEnableVertexAttribArray");
        pfn_glFinish = LoadRequiredFunction(functionLoader, "glFinish");
        pfn_glFlush = LoadRequiredFunction(functionLoader, "glFlush");
        pfn_glFramebufferTexture2D = LoadRequiredFunction(functionLoader, "glFramebufferTexture2D");
        pfn_glGenBuffers = LoadRequiredFunction(functionLoader, "glGenBuffers");
        pfn_glGenerateMipmap = LoadRequiredFunction(functionLoader, "glGenerateMipmap");
        pfn_glGenFramebuffers = LoadRequiredFunction(functionLoader, "glGenFramebuffers");
        pfn_glGenTextures = LoadRequiredFunction(functionLoader, "glGenTextures");
        pfn_glGetBufferParameteriv = LoadRequiredFunction(functionLoader, "glGetBufferParameteriv");
        pfn_glGetIntegerv = LoadRequiredFunction(functionLoader, "glGetIntegerv");
        pfn_glGetProgramiv = LoadRequiredFunction(functionLoader, "glGetProgramiv");
        pfn_glGetProgramInfoLog = LoadRequiredFunction(functionLoader, "glGetProgramInfoLog");
        pfn_glGetShaderiv = LoadRequiredFunction(functionLoader, "glGetShaderiv");
        pfn_glGetShaderInfoLog = LoadRequiredFunction(functionLoader, "glGetShaderInfoLog");
        pfn_glGetUniformLocation = LoadRequiredFunction(functionLoader, "glGetUniformLocation");
        pfn_glLinkProgram = LoadRequiredFunction(functionLoader, "glLinkProgram");
        pfn_glPixelStorei = LoadRequiredFunction(functionLoader, "glPixelStorei");
        pfn_glReadPixels = LoadRequiredFunction(functionLoader, "glReadPixels");
        pfn_glShaderSource = LoadRequiredFunction(functionLoader, "glShaderSource");
        pfn_glStencilFunc = LoadRequiredFunction(functionLoader, "glStencilFunc");
        pfn_glStencilMask = LoadRequiredFunction(functionLoader, "glStencilMask");
        pfn_glStencilOp = LoadRequiredFunction(functionLoader, "glStencilOp");
        pfn_glTexImage2D = LoadRequiredFunction(functionLoader, "glTexImage2D");
        pfn_glTexParameteri = LoadRequiredFunction(functionLoader, "glTexParameteri");
        pfn_glTexSubImage2D = LoadRequiredFunction(functionLoader, "glTexSubImage2D");
        pfn_glUniform1f = LoadRequiredFunction(functionLoader, "glUniform1f");
        pfn_glUniform1fv = LoadRequiredFunction(functionLoader, "glUniform1fv");
        pfn_glUniform1i = LoadRequiredFunction(functionLoader, "glUniform1i");
        pfn_glUniform1iv = LoadRequiredFunction(functionLoader, "glUniform1iv");
        pfn_glUniform2fv = LoadRequiredFunction(functionLoader, "glUniform2fv");
        pfn_glUniform2iv = LoadRequiredFunction(functionLoader, "glUniform2iv");
        pfn_glUniform3fv = LoadRequiredFunction(functionLoader, "glUniform3fv");
        pfn_glUniform3iv = LoadRequiredFunction(functionLoader, "glUniform3iv");
        pfn_glUniform4f = LoadRequiredFunction(functionLoader, "glUniform4f");
        pfn_glUniform4fv = LoadRequiredFunction(functionLoader, "glUniform4fv");
        pfn_glUniform4iv = LoadRequiredFunction(functionLoader, "glUniform4iv");
        pfn_glUniformMatrix4fv = LoadRequiredFunction(functionLoader, "glUniformMatrix4fv");
        pfn_glUseProgram = LoadRequiredFunction(functionLoader, "glUseProgram");
        pfn_glVertexAttribPointer = LoadRequiredFunction(functionLoader, "glVertexAttribPointer");
        pfn_glViewport = LoadRequiredFunction(functionLoader, "glViewport");
        pfn_glUnmapBuffer = LoadRequiredFunction(functionLoader, "glUnmapBuffer");
        pfn_glUniformMatrix3x2fv = LoadRequiredFunction(functionLoader, "glUniformMatrix3x2fv");
        pfn_glBlitFramebuffer = LoadRequiredFunction(functionLoader, "glBlitFramebuffer");
        pfn_glMapBufferRange = LoadRequiredFunction(functionLoader, "glMapBufferRange");
        pfn_glBindVertexArray = LoadRequiredFunction(functionLoader, "glBindVertexArray");
        pfn_glDeleteVertexArrays = LoadRequiredFunction(functionLoader, "glDeleteVertexArrays");
        pfn_glGenVertexArrays = LoadRequiredFunction(functionLoader, "glGenVertexArrays");
        pfn_glBindBufferBase = LoadRequiredFunction(functionLoader, "glBindBufferBase");
        pfn_glUniform1ui = LoadRequiredFunction(functionLoader, "glUniform1ui");
        pfn_glUniform3ui = LoadRequiredFunction(functionLoader, "glUniform3ui");
        pfn_glDrawArraysInstanced = LoadRequiredFunction(functionLoader, "glDrawArraysInstanced");
        pfn_glDrawElementsInstanced = LoadRequiredFunction(functionLoader, "glDrawElementsInstanced");
        pfn_glVertexAttribDivisor = LoadRequiredFunction(functionLoader, "glVertexAttribDivisor");
        pfn_glDispatchCompute = LoadOptionalFunction(functionLoader, "glDispatchCompute");
        pfn_glGetProgramResourceIndex = LoadRequiredFunction(functionLoader, "glGetProgramResourceIndex");
        pfn_glGetProgramResourceiv = LoadRequiredFunction(functionLoader, "glGetProgramResourceiv");
        pfn_glMemoryBarrier = LoadRequiredFunction(functionLoader, "glMemoryBarrier");
        pfn_glMemoryBarrier = LoadOptionalFunction(functionLoader, "glMemoryBarrier");
        pfn_glDebugMessageCallback = LoadOptionalFunction(functionLoader, "glDebugMessageCallback");
        pfn_glFramebufferTexture = LoadRequiredFunction(functionLoader, "glFramebufferTexture");
    }
    public const uint GL_GLES_PROTOTYPES = 1;
    public const uint GL_ES_VERSION_2_0 = 1;
    public const uint GL_DEPTH_BUFFER_BIT = 0x00000100;
    public const uint GL_STENCIL_BUFFER_BIT = 0x00000400;
    public const uint GL_COLOR_BUFFER_BIT = 0x00004000;
    public const uint GL_FALSE = 0;
    public const uint GL_TRUE = 1;
    public const uint GL_POINTS = 0x0000;
    public const uint GL_LINES = 0x0001;
    public const uint GL_LINE_LOOP = 0x0002;
    public const uint GL_LINE_STRIP = 0x0003;
    public const uint GL_TRIANGLES = 0x0004;
    public const uint GL_TRIANGLE_STRIP = 0x0005;
    public const uint GL_TRIANGLE_FAN = 0x0006;
    public const uint GL_ZERO = 0;
    public const uint GL_ONE = 1;
    public const uint GL_SRC_COLOR = 0x0300;
    public const uint GL_ONE_MINUS_SRC_COLOR = 0x0301;
    public const uint GL_SRC_ALPHA = 0x0302;
    public const uint GL_ONE_MINUS_SRC_ALPHA = 0x0303;
    public const uint GL_DST_ALPHA = 0x0304;
    public const uint GL_ONE_MINUS_DST_ALPHA = 0x0305;
    public const uint GL_DST_COLOR = 0x0306;
    public const uint GL_ONE_MINUS_DST_COLOR = 0x0307;
    public const uint GL_SRC_ALPHA_SATURATE = 0x0308;
    public const uint GL_FUNC_ADD = 0x8006;
    public const uint GL_BLEND_EQUATION = 0x8009;
    public const uint GL_BLEND_EQUATION_RGB = 0x8009;
    public const uint GL_BLEND_EQUATION_ALPHA = 0x883D;
    public const uint GL_FUNC_SUBTRACT = 0x800A;
    public const uint GL_FUNC_REVERSE_SUBTRACT = 0x800B;
    public const uint GL_BLEND_DST_RGB = 0x80C8;
    public const uint GL_BLEND_SRC_RGB = 0x80C9;
    public const uint GL_BLEND_DST_ALPHA = 0x80CA;
    public const uint GL_BLEND_SRC_ALPHA = 0x80CB;
    public const uint GL_CONSTANT_COLOR = 0x8001;
    public const uint GL_ONE_MINUS_CONSTANT_COLOR = 0x8002;
    public const uint GL_CONSTANT_ALPHA = 0x8003;
    public const uint GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004;
    public const uint GL_BLEND_COLOR = 0x8005;
    public const uint GL_ARRAY_BUFFER = 0x8892;
    public const uint GL_ELEMENT_ARRAY_BUFFER = 0x8893;
    public const uint GL_ARRAY_BUFFER_BINDING = 0x8894;
    public const uint GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895;
    public const uint GL_STREAM_DRAW = 0x88E0;
    public const uint GL_STATIC_DRAW = 0x88E4;
    public const uint GL_DYNAMIC_DRAW = 0x88E8;
    public const uint GL_BUFFER_SIZE = 0x8764;
    public const uint GL_BUFFER_USAGE = 0x8765;
    public const uint GL_CURRENT_VERTEX_ATTRIB = 0x8626;
    public const uint GL_FRONT = 0x0404;
    public const uint GL_BACK = 0x0405;
    public const uint GL_FRONT_AND_BACK = 0x0408;
    public const uint GL_TEXTURE_2D = 0x0DE1;
    public const uint GL_CULL_FACE = 0x0B44;
    public const uint GL_BLEND = 0x0BE2;
    public const uint GL_DITHER = 0x0BD0;
    public const uint GL_STENCIL_TEST = 0x0B90;
    public const uint GL_DEPTH_TEST = 0x0B71;
    public const uint GL_SCISSOR_TEST = 0x0C11;
    public const uint GL_POLYGON_OFFSET_FILL = 0x8037;
    public const uint GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E;
    public const uint GL_SAMPLE_COVERAGE = 0x80A0;
    public const uint GL_NO_ERROR = 0;
    public const uint GL_INVALID_ENUM = 0x0500;
    public const uint GL_INVALID_VALUE = 0x0501;
    public const uint GL_INVALID_OPERATION = 0x0502;
    public const uint GL_OUT_OF_MEMORY = 0x0505;
    public const uint GL_CW = 0x0900;
    public const uint GL_CCW = 0x0901;
    public const uint GL_LINE_WIDTH = 0x0B21;
    public const uint GL_ALIASED_POINT_SIZE_RANGE = 0x846D;
    public const uint GL_ALIASED_LINE_WIDTH_RANGE = 0x846E;
    public const uint GL_CULL_FACE_MODE = 0x0B45;
    public const uint GL_FRONT_FACE = 0x0B46;
    public const uint GL_DEPTH_RANGE = 0x0B70;
    public const uint GL_DEPTH_WRITEMASK = 0x0B72;
    public const uint GL_DEPTH_CLEAR_VALUE = 0x0B73;
    public const uint GL_DEPTH_FUNC = 0x0B74;
    public const uint GL_STENCIL_CLEAR_VALUE = 0x0B91;
    public const uint GL_STENCIL_FUNC = 0x0B92;
    public const uint GL_STENCIL_FAIL = 0x0B94;
    public const uint GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95;
    public const uint GL_STENCIL_PASS_DEPTH_PASS = 0x0B96;
    public const uint GL_STENCIL_REF = 0x0B97;
    public const uint GL_STENCIL_VALUE_MASK = 0x0B93;
    public const uint GL_STENCIL_WRITEMASK = 0x0B98;
    public const uint GL_STENCIL_BACK_FUNC = 0x8800;
    public const uint GL_STENCIL_BACK_FAIL = 0x8801;
    public const uint GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802;
    public const uint GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803;
    public const uint GL_STENCIL_BACK_REF = 0x8CA3;
    public const uint GL_STENCIL_BACK_VALUE_MASK = 0x8CA4;
    public const uint GL_STENCIL_BACK_WRITEMASK = 0x8CA5;
    public const uint GL_VIEWPORT = 0x0BA2;
    public const uint GL_SCISSOR_BOX = 0x0C10;
    public const uint GL_COLOR_CLEAR_VALUE = 0x0C22;
    public const uint GL_COLOR_WRITEMASK = 0x0C23;
    public const uint GL_UNPACK_ALIGNMENT = 0x0CF5;
    public const uint GL_PACK_ALIGNMENT = 0x0D05;
    public const uint GL_MAX_TEXTURE_SIZE = 0x0D33;
    public const uint GL_MAX_VIEWPORT_DIMS = 0x0D3A;
    public const uint GL_SUBPIXEL_BITS = 0x0D50;
    public const uint GL_RED_BITS = 0x0D52;
    public const uint GL_GREEN_BITS = 0x0D53;
    public const uint GL_BLUE_BITS = 0x0D54;
    public const uint GL_ALPHA_BITS = 0x0D55;
    public const uint GL_DEPTH_BITS = 0x0D56;
    public const uint GL_STENCIL_BITS = 0x0D57;
    public const uint GL_POLYGON_OFFSET_UNITS = 0x2A00;
    public const uint GL_POLYGON_OFFSET_FACTOR = 0x8038;
    public const uint GL_TEXTURE_BINDING_2D = 0x8069;
    public const uint GL_SAMPLE_BUFFERS = 0x80A8;
    public const uint GL_SAMPLES = 0x80A9;
    public const uint GL_SAMPLE_COVERAGE_VALUE = 0x80AA;
    public const uint GL_SAMPLE_COVERAGE_INVERT = 0x80AB;
    public const uint GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2;
    public const uint GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3;
    public const uint GL_DONT_CARE = 0x1100;
    public const uint GL_FASTEST = 0x1101;
    public const uint GL_NICEST = 0x1102;
    public const uint GL_GENERATE_MIPMAP_HINT = 0x8192;
    public const uint GL_BYTE = 0x1400;
    public const uint GL_UNSIGNED_BYTE = 0x1401;
    public const uint GL_SHORT = 0x1402;
    public const uint GL_UNSIGNED_SHORT = 0x1403;
    public const uint GL_INT = 0x1404;
    public const uint GL_UNSIGNED_INT = 0x1405;
    public const uint GL_FLOAT = 0x1406;
    public const uint GL_FIXED = 0x140C;
    public const uint GL_DEPTH_COMPONENT = 0x1902;
    public const uint GL_ALPHA = 0x1906;
    public const uint GL_RGB = 0x1907;
    public const uint GL_RGBA = 0x1908;
    public const uint GL_LUMINANCE = 0x1909;
    public const uint GL_LUMINANCE_ALPHA = 0x190A;
    public const uint GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033;
    public const uint GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034;
    public const uint GL_UNSIGNED_SHORT_5_6_5 = 0x8363;
    public const uint GL_FRAGMENT_SHADER = 0x8B30;
    public const uint GL_VERTEX_SHADER = 0x8B31;
    public const uint GL_MAX_VERTEX_ATTRIBS = 0x8869;
    public const uint GL_MAX_VERTEX_UNIFORM_VECTORS = 0x8DFB;
    public const uint GL_MAX_VARYING_VECTORS = 0x8DFC;
    public const uint GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D;
    public const uint GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C;
    public const uint GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872;
    public const uint GL_MAX_FRAGMENT_UNIFORM_VECTORS = 0x8DFD;
    public const uint GL_SHADER_TYPE = 0x8B4F;
    public const uint GL_DELETE_STATUS = 0x8B80;
    public const uint GL_LINK_STATUS = 0x8B82;
    public const uint GL_VALIDATE_STATUS = 0x8B83;
    public const uint GL_ATTACHED_SHADERS = 0x8B85;
    public const uint GL_ACTIVE_UNIFORMS = 0x8B86;
    public const uint GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87;
    public const uint GL_ACTIVE_ATTRIBUTES = 0x8B89;
    public const uint GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A;
    public const uint GL_SHADING_LANGUAGE_VERSION = 0x8B8C;
    public const uint GL_CURRENT_PROGRAM = 0x8B8D;
    public const uint GL_NEVER = 0x0200;
    public const uint GL_LESS = 0x0201;
    public const uint GL_EQUAL = 0x0202;
    public const uint GL_LEQUAL = 0x0203;
    public const uint GL_GREATER = 0x0204;
    public const uint GL_NOTEQUAL = 0x0205;
    public const uint GL_GEQUAL = 0x0206;
    public const uint GL_ALWAYS = 0x0207;
    public const uint GL_KEEP = 0x1E00;
    public const uint GL_REPLACE = 0x1E01;
    public const uint GL_INCR = 0x1E02;
    public const uint GL_DECR = 0x1E03;
    public const uint GL_INVERT = 0x150A;
    public const uint GL_INCR_WRAP = 0x8507;
    public const uint GL_DECR_WRAP = 0x8508;
    public const uint GL_VENDOR = 0x1F00;
    public const uint GL_RENDERER = 0x1F01;
    public const uint GL_VERSION = 0x1F02;
    public const uint GL_NEAREST = 0x2600;
    public const uint GL_LINEAR = 0x2601;
    public const uint GL_NEAREST_MIPMAP_NEAREST = 0x2700;
    public const uint GL_LINEAR_MIPMAP_NEAREST = 0x2701;
    public const uint GL_NEAREST_MIPMAP_LINEAR = 0x2702;
    public const uint GL_LINEAR_MIPMAP_LINEAR = 0x2703;
    public const uint GL_TEXTURE_MAG_FILTER = 0x2800;
    public const uint GL_TEXTURE_MIN_FILTER = 0x2801;
    public const uint GL_TEXTURE_WRAP_S = 0x2802;
    public const uint GL_TEXTURE_WRAP_T = 0x2803;
    public const uint GL_TEXTURE = 0x1702;
    public const uint GL_TEXTURE_CUBE_MAP = 0x8513;
    public const uint GL_TEXTURE_BINDING_CUBE_MAP = 0x8514;
    public const uint GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515;
    public const uint GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516;
    public const uint GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517;
    public const uint GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518;
    public const uint GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519;
    public const uint GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A;
    public const uint GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C;
    public const uint GL_TEXTURE0 = 0x84C0;
    public const uint GL_TEXTURE1 = 0x84C1;
    public const uint GL_TEXTURE2 = 0x84C2;
    public const uint GL_TEXTURE3 = 0x84C3;
    public const uint GL_TEXTURE4 = 0x84C4;
    public const uint GL_TEXTURE5 = 0x84C5;
    public const uint GL_TEXTURE6 = 0x84C6;
    public const uint GL_TEXTURE7 = 0x84C7;
    public const uint GL_TEXTURE8 = 0x84C8;
    public const uint GL_TEXTURE9 = 0x84C9;
    public const uint GL_TEXTURE10 = 0x84CA;
    public const uint GL_TEXTURE11 = 0x84CB;
    public const uint GL_TEXTURE12 = 0x84CC;
    public const uint GL_TEXTURE13 = 0x84CD;
    public const uint GL_TEXTURE14 = 0x84CE;
    public const uint GL_TEXTURE15 = 0x84CF;
    public const uint GL_TEXTURE16 = 0x84D0;
    public const uint GL_TEXTURE17 = 0x84D1;
    public const uint GL_TEXTURE18 = 0x84D2;
    public const uint GL_TEXTURE19 = 0x84D3;
    public const uint GL_TEXTURE20 = 0x84D4;
    public const uint GL_TEXTURE21 = 0x84D5;
    public const uint GL_TEXTURE22 = 0x84D6;
    public const uint GL_TEXTURE23 = 0x84D7;
    public const uint GL_TEXTURE24 = 0x84D8;
    public const uint GL_TEXTURE25 = 0x84D9;
    public const uint GL_TEXTURE26 = 0x84DA;
    public const uint GL_TEXTURE27 = 0x84DB;
    public const uint GL_TEXTURE28 = 0x84DC;
    public const uint GL_TEXTURE29 = 0x84DD;
    public const uint GL_TEXTURE30 = 0x84DE;
    public const uint GL_TEXTURE31 = 0x84DF;
    public const uint GL_ACTIVE_TEXTURE = 0x84E0;
    public const uint GL_REPEAT = 0x2901;
    public const uint GL_CLAMP_TO_EDGE = 0x812F;
    public const uint GL_MIRRORED_REPEAT = 0x8370;
    public const uint GL_FLOAT_VEC2 = 0x8B50;
    public const uint GL_FLOAT_VEC3 = 0x8B51;
    public const uint GL_FLOAT_VEC4 = 0x8B52;
    public const uint GL_INT_VEC2 = 0x8B53;
    public const uint GL_INT_VEC3 = 0x8B54;
    public const uint GL_INT_VEC4 = 0x8B55;
    public const uint GL_BOOL = 0x8B56;
    public const uint GL_BOOL_VEC2 = 0x8B57;
    public const uint GL_BOOL_VEC3 = 0x8B58;
    public const uint GL_BOOL_VEC4 = 0x8B59;
    public const uint GL_FLOAT_MAT2 = 0x8B5A;
    public const uint GL_FLOAT_MAT3 = 0x8B5B;
    public const uint GL_FLOAT_MAT4 = 0x8B5C;
    public const uint GL_SAMPLER_2D = 0x8B5E;
    public const uint GL_SAMPLER_CUBE = 0x8B60;
    public const uint GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622;
    public const uint GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623;
    public const uint GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624;
    public const uint GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625;
    public const uint GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A;
    public const uint GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645;
    public const uint GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F;
    public const uint GL_IMPLEMENTATION_COLOR_READ_TYPE = 0x8B9A;
    public const uint GL_IMPLEMENTATION_COLOR_READ_FORMAT = 0x8B9B;
    public const uint GL_COMPILE_STATUS = 0x8B81;
    public const uint GL_INFO_LOG_LENGTH = 0x8B84;
    public const uint GL_SHADER_SOURCE_LENGTH = 0x8B88;
    public const uint GL_SHADER_COMPILER = 0x8DFA;
    public const uint GL_SHADER_BINARY_FORMATS = 0x8DF8;
    public const uint GL_NUM_SHADER_BINARY_FORMATS = 0x8DF9;
    public const uint GL_LOW_FLOAT = 0x8DF0;
    public const uint GL_MEDIUM_FLOAT = 0x8DF1;
    public const uint GL_HIGH_FLOAT = 0x8DF2;
    public const uint GL_LOW_INT = 0x8DF3;
    public const uint GL_MEDIUM_INT = 0x8DF4;
    public const uint GL_HIGH_INT = 0x8DF5;
    public const uint GL_FRAMEBUFFER = 0x8D40;
    public const uint GL_RENDERBUFFER = 0x8D41;
    public const uint GL_RGBA4 = 0x8056;
    public const uint GL_RGB5_A1 = 0x8057;
    public const uint GL_RGB565 = 0x8D62;
    public const uint GL_DEPTH_COMPONENT16 = 0x81A5;
    public const uint GL_STENCIL_INDEX8 = 0x8D48;
    public const uint GL_RENDERBUFFER_WIDTH = 0x8D42;
    public const uint GL_RENDERBUFFER_HEIGHT = 0x8D43;
    public const uint GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44;
    public const uint GL_RENDERBUFFER_RED_SIZE = 0x8D50;
    public const uint GL_RENDERBUFFER_GREEN_SIZE = 0x8D51;
    public const uint GL_RENDERBUFFER_BLUE_SIZE = 0x8D52;
    public const uint GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53;
    public const uint GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54;
    public const uint GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3;
    public const uint GL_COLOR_ATTACHMENT0 = 0x8CE0;
    public const uint GL_DEPTH_ATTACHMENT = 0x8D00;
    public const uint GL_STENCIL_ATTACHMENT = 0x8D20;
    public const uint GL_NONE = 0;
    public const uint GL_FRAMEBUFFER_COMPLETE = 0x8CD5;
    public const uint GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6;
    public const uint GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7;
    public const uint GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS = 0x8CD9;
    public const uint GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD;
    public const uint GL_FRAMEBUFFER_BINDING = 0x8CA6;
    public const uint GL_RENDERBUFFER_BINDING = 0x8CA7;
    public const uint GL_MAX_RENDERBUFFER_SIZE = 0x84E8;
    public const uint GL_INVALID_FRAMEBUFFER_OPERATION = 0x0506;
    public const uint GL_ES_VERSION_3_0 = 1;
    public const uint GL_READ_BUFFER = 0x0C02;
    public const uint GL_UNPACK_ROW_LENGTH = 0x0CF2;
    public const uint GL_UNPACK_SKIP_ROWS = 0x0CF3;
    public const uint GL_UNPACK_SKIP_PIXELS = 0x0CF4;
    public const uint GL_PACK_ROW_LENGTH = 0x0D02;
    public const uint GL_PACK_SKIP_ROWS = 0x0D03;
    public const uint GL_PACK_SKIP_PIXELS = 0x0D04;
    public const uint GL_COLOR = 0x1800;
    public const uint GL_DEPTH = 0x1801;
    public const uint GL_STENCIL = 0x1802;
    public const uint GL_RED = 0x1903;
    public const uint GL_RGB8 = 0x8051;
    public const uint GL_RGBA8 = 0x8058;
    public const uint GL_RGB10_A2 = 0x8059;
    public const uint GL_TEXTURE_BINDING_3D = 0x806A;
    public const uint GL_UNPACK_SKIP_IMAGES = 0x806D;
    public const uint GL_UNPACK_IMAGE_HEIGHT = 0x806E;
    public const uint GL_TEXTURE_3D = 0x806F;
    public const uint GL_TEXTURE_WRAP_R = 0x8072;
    public const uint GL_MAX_3D_TEXTURE_SIZE = 0x8073;
    public const uint GL_UNSIGNED_INT_2_10_10_10_REV = 0x8368;
    public const uint GL_MAX_ELEMENTS_VERTICES = 0x80E8;
    public const uint GL_MAX_ELEMENTS_INDICES = 0x80E9;
    public const uint GL_TEXTURE_MIN_LOD = 0x813A;
    public const uint GL_TEXTURE_MAX_LOD = 0x813B;
    public const uint GL_TEXTURE_BASE_LEVEL = 0x813C;
    public const uint GL_TEXTURE_MAX_LEVEL = 0x813D;
    public const uint GL_MIN = 0x8007;
    public const uint GL_MAX = 0x8008;
    public const uint GL_DEPTH_COMPONENT24 = 0x81A6;
    public const uint GL_MAX_TEXTURE_LOD_BIAS = 0x84FD;
    public const uint GL_TEXTURE_COMPARE_MODE = 0x884C;
    public const uint GL_TEXTURE_COMPARE_FUNC = 0x884D;
    public const uint GL_CURRENT_QUERY = 0x8865;
    public const uint GL_QUERY_RESULT = 0x8866;
    public const uint GL_QUERY_RESULT_AVAILABLE = 0x8867;
    public const uint GL_BUFFER_MAPPED = 0x88BC;
    public const uint GL_BUFFER_MAP_POINTER = 0x88BD;
    public const uint GL_STREAM_READ = 0x88E1;
    public const uint GL_STREAM_COPY = 0x88E2;
    public const uint GL_STATIC_READ = 0x88E5;
    public const uint GL_STATIC_COPY = 0x88E6;
    public const uint GL_DYNAMIC_READ = 0x88E9;
    public const uint GL_DYNAMIC_COPY = 0x88EA;
    public const uint GL_MAX_DRAW_BUFFERS = 0x8824;
    public const uint GL_DRAW_BUFFER0 = 0x8825;
    public const uint GL_DRAW_BUFFER1 = 0x8826;
    public const uint GL_DRAW_BUFFER2 = 0x8827;
    public const uint GL_DRAW_BUFFER3 = 0x8828;
    public const uint GL_DRAW_BUFFER4 = 0x8829;
    public const uint GL_DRAW_BUFFER5 = 0x882A;
    public const uint GL_DRAW_BUFFER6 = 0x882B;
    public const uint GL_DRAW_BUFFER7 = 0x882C;
    public const uint GL_DRAW_BUFFER8 = 0x882D;
    public const uint GL_DRAW_BUFFER9 = 0x882E;
    public const uint GL_DRAW_BUFFER10 = 0x882F;
    public const uint GL_DRAW_BUFFER11 = 0x8830;
    public const uint GL_DRAW_BUFFER12 = 0x8831;
    public const uint GL_DRAW_BUFFER13 = 0x8832;
    public const uint GL_DRAW_BUFFER14 = 0x8833;
    public const uint GL_DRAW_BUFFER15 = 0x8834;
    public const uint GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49;
    public const uint GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A;
    public const uint GL_SAMPLER_3D = 0x8B5F;
    public const uint GL_SAMPLER_2D_SHADOW = 0x8B62;
    public const uint GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B;
    public const uint GL_PIXEL_PACK_BUFFER = 0x88EB;
    public const uint GL_PIXEL_UNPACK_BUFFER = 0x88EC;
    public const uint GL_PIXEL_PACK_BUFFER_BINDING = 0x88ED;
    public const uint GL_PIXEL_UNPACK_BUFFER_BINDING = 0x88EF;
    public const uint GL_FLOAT_MAT2x3 = 0x8B65;
    public const uint GL_FLOAT_MAT2x4 = 0x8B66;
    public const uint GL_FLOAT_MAT3x2 = 0x8B67;
    public const uint GL_FLOAT_MAT3x4 = 0x8B68;
    public const uint GL_FLOAT_MAT4x2 = 0x8B69;
    public const uint GL_FLOAT_MAT4x3 = 0x8B6A;
    public const uint GL_SRGB = 0x8C40;
    public const uint GL_SRGB8 = 0x8C41;
    public const uint GL_SRGB8_ALPHA8 = 0x8C43;
    public const uint GL_COMPARE_REF_TO_TEXTURE = 0x884E;
    public const uint GL_MAJOR_VERSION = 0x821B;
    public const uint GL_MINOR_VERSION = 0x821C;
    public const uint GL_NUM_EXTENSIONS = 0x821D;
    public const uint GL_RGBA32F = 0x8814;
    public const uint GL_RGB32F = 0x8815;
    public const uint GL_RGBA16F = 0x881A;
    public const uint GL_RGB16F = 0x881B;
    public const uint GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD;
    public const uint GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF;
    public const uint GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904;
    public const uint GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905;
    public const uint GL_MAX_VARYING_COMPONENTS = 0x8B4B;
    public const uint GL_TEXTURE_2D_ARRAY = 0x8C1A;
    public const uint GL_TEXTURE_BINDING_2D_ARRAY = 0x8C1D;
    public const uint GL_R11F_G11F_B10F = 0x8C3A;
    public const uint GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B;
    public const uint GL_RGB9_E5 = 0x8C3D;
    public const uint GL_UNSIGNED_INT_5_9_9_9_REV = 0x8C3E;
    public const uint GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8C76;
    public const uint GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8C7F;
    public const uint GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8C80;
    public const uint GL_TRANSFORM_FEEDBACK_VARYINGS = 0x8C83;
    public const uint GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x8C84;
    public const uint GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8C85;
    public const uint GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88;
    public const uint GL_RASTERIZER_DISCARD = 0x8C89;
    public const uint GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A;
    public const uint GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8C8B;
    public const uint GL_INTERLEAVED_ATTRIBS = 0x8C8C;
    public const uint GL_SEPARATE_ATTRIBS = 0x8C8D;
    public const uint GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E;
    public const uint GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8C8F;
    public const uint GL_RGBA32UI = 0x8D70;
    public const uint GL_RGB32UI = 0x8D71;
    public const uint GL_RGBA16UI = 0x8D76;
    public const uint GL_RGB16UI = 0x8D77;
    public const uint GL_RGBA8UI = 0x8D7C;
    public const uint GL_RGB8UI = 0x8D7D;
    public const uint GL_RGBA32I = 0x8D82;
    public const uint GL_RGB32I = 0x8D83;
    public const uint GL_RGBA16I = 0x8D88;
    public const uint GL_RGB16I = 0x8D89;
    public const uint GL_RGBA8I = 0x8D8E;
    public const uint GL_RGB8I = 0x8D8F;
    public const uint GL_RED_INTEGER = 0x8D94;
    public const uint GL_RGB_INTEGER = 0x8D98;
    public const uint GL_RGBA_INTEGER = 0x8D99;
    public const uint GL_SAMPLER_2D_ARRAY = 0x8DC1;
    public const uint GL_SAMPLER_2D_ARRAY_SHADOW = 0x8DC4;
    public const uint GL_SAMPLER_CUBE_SHADOW = 0x8DC5;
    public const uint GL_UNSIGNED_INT_VEC2 = 0x8DC6;
    public const uint GL_UNSIGNED_INT_VEC3 = 0x8DC7;
    public const uint GL_UNSIGNED_INT_VEC4 = 0x8DC8;
    public const uint GL_INT_SAMPLER_2D = 0x8DCA;
    public const uint GL_INT_SAMPLER_3D = 0x8DCB;
    public const uint GL_INT_SAMPLER_CUBE = 0x8DCC;
    public const uint GL_INT_SAMPLER_2D_ARRAY = 0x8DCF;
    public const uint GL_UNSIGNED_INT_SAMPLER_2D = 0x8DD2;
    public const uint GL_UNSIGNED_INT_SAMPLER_3D = 0x8DD3;
    public const uint GL_UNSIGNED_INT_SAMPLER_CUBE = 0x8DD4;
    public const uint GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8DD7;
    public const uint GL_BUFFER_ACCESS_FLAGS = 0x911F;
    public const uint GL_BUFFER_MAP_LENGTH = 0x9120;
    public const uint GL_BUFFER_MAP_OFFSET = 0x9121;
    public const uint GL_DEPTH_COMPONENT32F = 0x8CAC;
    public const uint GL_DEPTH32F_STENCIL8 = 0x8CAD;
    public const uint GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217;
    public const uint GL_FRAMEBUFFER_DEFAULT = 0x8218;
    public const uint GL_FRAMEBUFFER_UNDEFINED = 0x8219;
    public const uint GL_DEPTH_STENCIL_ATTACHMENT = 0x821A;
    public const uint GL_DEPTH_STENCIL = 0x84F9;
    public const uint GL_UNSIGNED_INT_24_8 = 0x84FA;
    public const uint GL_DEPTH24_STENCIL8 = 0x88F0;
    public const uint GL_UNSIGNED_NORMALIZED = 0x8C17;
    public const uint GL_DRAW_FRAMEBUFFER_BINDING = 0x8CA6;
    public const uint GL_READ_FRAMEBUFFER = 0x8CA8;
    public const uint GL_DRAW_FRAMEBUFFER = 0x8CA9;
    public const uint GL_READ_FRAMEBUFFER_BINDING = 0x8CAA;
    public const uint GL_RENDERBUFFER_SAMPLES = 0x8CAB;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4;
    public const uint GL_MAX_COLOR_ATTACHMENTS = 0x8CDF;
    public const uint GL_COLOR_ATTACHMENT1 = 0x8CE1;
    public const uint GL_COLOR_ATTACHMENT2 = 0x8CE2;
    public const uint GL_COLOR_ATTACHMENT3 = 0x8CE3;
    public const uint GL_COLOR_ATTACHMENT4 = 0x8CE4;
    public const uint GL_COLOR_ATTACHMENT5 = 0x8CE5;
    public const uint GL_COLOR_ATTACHMENT6 = 0x8CE6;
    public const uint GL_COLOR_ATTACHMENT7 = 0x8CE7;
    public const uint GL_COLOR_ATTACHMENT8 = 0x8CE8;
    public const uint GL_COLOR_ATTACHMENT9 = 0x8CE9;
    public const uint GL_COLOR_ATTACHMENT10 = 0x8CEA;
    public const uint GL_COLOR_ATTACHMENT11 = 0x8CEB;
    public const uint GL_COLOR_ATTACHMENT12 = 0x8CEC;
    public const uint GL_COLOR_ATTACHMENT13 = 0x8CED;
    public const uint GL_COLOR_ATTACHMENT14 = 0x8CEE;
    public const uint GL_COLOR_ATTACHMENT15 = 0x8CEF;
    public const uint GL_COLOR_ATTACHMENT16 = 0x8CF0;
    public const uint GL_COLOR_ATTACHMENT17 = 0x8CF1;
    public const uint GL_COLOR_ATTACHMENT18 = 0x8CF2;
    public const uint GL_COLOR_ATTACHMENT19 = 0x8CF3;
    public const uint GL_COLOR_ATTACHMENT20 = 0x8CF4;
    public const uint GL_COLOR_ATTACHMENT21 = 0x8CF5;
    public const uint GL_COLOR_ATTACHMENT22 = 0x8CF6;
    public const uint GL_COLOR_ATTACHMENT23 = 0x8CF7;
    public const uint GL_COLOR_ATTACHMENT24 = 0x8CF8;
    public const uint GL_COLOR_ATTACHMENT25 = 0x8CF9;
    public const uint GL_COLOR_ATTACHMENT26 = 0x8CFA;
    public const uint GL_COLOR_ATTACHMENT27 = 0x8CFB;
    public const uint GL_COLOR_ATTACHMENT28 = 0x8CFC;
    public const uint GL_COLOR_ATTACHMENT29 = 0x8CFD;
    public const uint GL_COLOR_ATTACHMENT30 = 0x8CFE;
    public const uint GL_COLOR_ATTACHMENT31 = 0x8CFF;
    public const uint GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56;
    public const uint GL_MAX_SAMPLES = 0x8D57;
    public const uint GL_HALF_FLOAT = 0x140B;
    public const uint GL_MAP_READ_BIT = 0x0001;
    public const uint GL_MAP_WRITE_BIT = 0x0002;
    public const uint GL_MAP_INVALIDATE_RANGE_BIT = 0x0004;
    public const uint GL_MAP_INVALIDATE_BUFFER_BIT = 0x0008;
    public const uint GL_MAP_FLUSH_EXPLICIT_BIT = 0x0010;
    public const uint GL_MAP_UNSYNCHRONIZED_BIT = 0x0020;
    public const uint GL_RG = 0x8227;
    public const uint GL_RG_INTEGER = 0x8228;
    public const uint GL_R8 = 0x8229;
    public const uint GL_RG8 = 0x822B;
    public const uint GL_R16F = 0x822D;
    public const uint GL_R32F = 0x822E;
    public const uint GL_RG16F = 0x822F;
    public const uint GL_RG32F = 0x8230;
    public const uint GL_R8I = 0x8231;
    public const uint GL_R8UI = 0x8232;
    public const uint GL_R16I = 0x8233;
    public const uint GL_R16UI = 0x8234;
    public const uint GL_R32I = 0x8235;
    public const uint GL_R32UI = 0x8236;
    public const uint GL_RG8I = 0x8237;
    public const uint GL_RG8UI = 0x8238;
    public const uint GL_RG16I = 0x8239;
    public const uint GL_RG16UI = 0x823A;
    public const uint GL_RG32I = 0x823B;
    public const uint GL_RG32UI = 0x823C;
    public const uint GL_VERTEX_ARRAY_BINDING = 0x85B5;
    public const uint GL_R8_SNORM = 0x8F94;
    public const uint GL_RG8_SNORM = 0x8F95;
    public const uint GL_RGB8_SNORM = 0x8F96;
    public const uint GL_RGBA8_SNORM = 0x8F97;
    public const uint GL_SIGNED_NORMALIZED = 0x8F9C;
    public const uint GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x8D69;
    public const uint GL_COPY_READ_BUFFER = 0x8F36;
    public const uint GL_COPY_WRITE_BUFFER = 0x8F37;
    public const uint GL_COPY_READ_BUFFER_BINDING = 0x8F36;
    public const uint GL_COPY_WRITE_BUFFER_BINDING = 0x8F37;
    public const uint GL_UNIFORM_BUFFER = 0x8A11;
    public const uint GL_UNIFORM_BUFFER_BINDING = 0x8A28;
    public const uint GL_UNIFORM_BUFFER_START = 0x8A29;
    public const uint GL_UNIFORM_BUFFER_SIZE = 0x8A2A;
    public const uint GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B;
    public const uint GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D;
    public const uint GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E;
    public const uint GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F;
    public const uint GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30;
    public const uint GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31;
    public const uint GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33;
    public const uint GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34;
    public const uint GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x8A35;
    public const uint GL_ACTIVE_UNIFORM_BLOCKS = 0x8A36;
    public const uint GL_UNIFORM_TYPE = 0x8A37;
    public const uint GL_UNIFORM_SIZE = 0x8A38;
    public const uint GL_UNIFORM_NAME_LENGTH = 0x8A39;
    public const uint GL_UNIFORM_BLOCK_INDEX = 0x8A3A;
    public const uint GL_UNIFORM_OFFSET = 0x8A3B;
    public const uint GL_UNIFORM_ARRAY_STRIDE = 0x8A3C;
    public const uint GL_UNIFORM_MATRIX_STRIDE = 0x8A3D;
    public const uint GL_UNIFORM_IS_ROW_MAJOR = 0x8A3E;
    public const uint GL_UNIFORM_BLOCK_BINDING = 0x8A3F;
    public const uint GL_UNIFORM_BLOCK_DATA_SIZE = 0x8A40;
    public const uint GL_UNIFORM_BLOCK_NAME_LENGTH = 0x8A41;
    public const uint GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x8A42;
    public const uint GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x8A43;
    public const uint GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x8A44;
    public const uint GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x8A46;
    public const uint GL_MAX_VERTEX_OUTPUT_COMPONENTS = 0x9122;
    public const uint GL_MAX_FRAGMENT_INPUT_COMPONENTS = 0x9125;
    public const uint GL_MAX_SERVER_WAIT_TIMEOUT = 0x9111;
    public const uint GL_OBJECT_TYPE = 0x9112;
    public const uint GL_SYNC_CONDITION = 0x9113;
    public const uint GL_SYNC_STATUS = 0x9114;
    public const uint GL_SYNC_FLAGS = 0x9115;
    public const uint GL_SYNC_FENCE = 0x9116;
    public const uint GL_SYNC_GPU_COMMANDS_COMPLETE = 0x9117;
    public const uint GL_UNSIGNALED = 0x9118;
    public const uint GL_SIGNALED = 0x9119;
    public const uint GL_ALREADY_SIGNALED = 0x911A;
    public const uint GL_TIMEOUT_EXPIRED = 0x911B;
    public const uint GL_CONDITION_SATISFIED = 0x911C;
    public const uint GL_WAIT_FAILED = 0x911D;
    public const uint GL_SYNC_FLUSH_COMMANDS_BIT = 0x00000001;
    public const uint GL_VERTEX_ATTRIB_ARRAY_DIVISOR = 0x88FE;
    public const uint GL_ANY_SAMPLES_PASSED = 0x8C2F;
    public const uint GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x8D6A;
    public const uint GL_SAMPLER_BINDING = 0x8919;
    public const uint GL_RGB10_A2UI = 0x906F;
    public const uint GL_TEXTURE_SWIZZLE_R = 0x8E42;
    public const uint GL_TEXTURE_SWIZZLE_G = 0x8E43;
    public const uint GL_TEXTURE_SWIZZLE_B = 0x8E44;
    public const uint GL_TEXTURE_SWIZZLE_A = 0x8E45;
    public const uint GL_GREEN = 0x1904;
    public const uint GL_BLUE = 0x1905;
    public const uint GL_INT_2_10_10_10_REV = 0x8D9F;
    public const uint GL_TRANSFORM_FEEDBACK = 0x8E22;
    public const uint GL_TRANSFORM_FEEDBACK_PAUSED = 0x8E23;
    public const uint GL_TRANSFORM_FEEDBACK_ACTIVE = 0x8E24;
    public const uint GL_TRANSFORM_FEEDBACK_BINDING = 0x8E25;
    public const uint GL_PROGRAM_BINARY_RETRIEVABLE_HINT = 0x8257;
    public const uint GL_PROGRAM_BINARY_LENGTH = 0x8741;
    public const uint GL_NUM_PROGRAM_BINARY_FORMATS = 0x87FE;
    public const uint GL_PROGRAM_BINARY_FORMATS = 0x87FF;
    public const uint GL_COMPRESSED_R11_EAC = 0x9270;
    public const uint GL_COMPRESSED_SIGNED_R11_EAC = 0x9271;
    public const uint GL_COMPRESSED_RG11_EAC = 0x9272;
    public const uint GL_COMPRESSED_SIGNED_RG11_EAC = 0x9273;
    public const uint GL_COMPRESSED_RGB8_ETC2 = 0x9274;
    public const uint GL_COMPRESSED_SRGB8_ETC2 = 0x9275;
    public const uint GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9276;
    public const uint GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9277;
    public const uint GL_COMPRESSED_RGBA8_ETC2_EAC = 0x9278;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x9279;
    public const uint GL_TEXTURE_IMMUTABLE_FORMAT = 0x912F;
    public const uint GL_MAX_ELEMENT_INDEX = 0x8D6B;
    public const uint GL_NUM_SAMPLE_COUNTS = 0x9380;
    public const uint GL_TEXTURE_IMMUTABLE_LEVELS = 0x82DF;
    public const uint GL_ES_VERSION_3_1 = 1;
    public const uint GL_COMPUTE_SHADER = 0x91B9;
    public const uint GL_MAX_COMPUTE_UNIFORM_BLOCKS = 0x91BB;
    public const uint GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x91BC;
    public const uint GL_MAX_COMPUTE_IMAGE_UNIFORMS = 0x91BD;
    public const uint GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 0x8262;
    public const uint GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 0x8263;
    public const uint GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 0x8264;
    public const uint GL_MAX_COMPUTE_ATOMIC_COUNTERS = 0x8265;
    public const uint GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 0x8266;
    public const uint GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 0x90EB;
    public const uint GL_MAX_COMPUTE_WORK_GROUP_COUNT = 0x91BE;
    public const uint GL_MAX_COMPUTE_WORK_GROUP_SIZE = 0x91BF;
    public const uint GL_COMPUTE_WORK_GROUP_SIZE = 0x8267;
    public const uint GL_DISPATCH_INDIRECT_BUFFER = 0x90EE;
    public const uint GL_DISPATCH_INDIRECT_BUFFER_BINDING = 0x90EF;
    public const uint GL_COMPUTE_SHADER_BIT = 0x00000020;
    public const uint GL_DRAW_INDIRECT_BUFFER = 0x8F3F;
    public const uint GL_DRAW_INDIRECT_BUFFER_BINDING = 0x8F43;
    public const uint GL_MAX_UNIFORM_LOCATIONS = 0x826E;
    public const uint GL_FRAMEBUFFER_DEFAULT_WIDTH = 0x9310;
    public const uint GL_FRAMEBUFFER_DEFAULT_HEIGHT = 0x9311;
    public const uint GL_FRAMEBUFFER_DEFAULT_SAMPLES = 0x9313;
    public const uint GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 0x9314;
    public const uint GL_MAX_FRAMEBUFFER_WIDTH = 0x9315;
    public const uint GL_MAX_FRAMEBUFFER_HEIGHT = 0x9316;
    public const uint GL_MAX_FRAMEBUFFER_SAMPLES = 0x9318;
    public const uint GL_UNIFORM = 0x92E1;
    public const uint GL_UNIFORM_BLOCK = 0x92E2;
    public const uint GL_PROGRAM_INPUT = 0x92E3;
    public const uint GL_PROGRAM_OUTPUT = 0x92E4;
    public const uint GL_BUFFER_VARIABLE = 0x92E5;
    public const uint GL_SHADER_STORAGE_BLOCK = 0x92E6;
    public const uint GL_ATOMIC_COUNTER_BUFFER = 0x92C0;
    public const uint GL_TRANSFORM_FEEDBACK_VARYING = 0x92F4;
    public const uint GL_ACTIVE_RESOURCES = 0x92F5;
    public const uint GL_MAX_NAME_LENGTH = 0x92F6;
    public const uint GL_MAX_NUM_ACTIVE_VARIABLES = 0x92F7;
    public const uint GL_NAME_LENGTH = 0x92F9;
    public const uint GL_TYPE = 0x92FA;
    public const uint GL_ARRAY_SIZE = 0x92FB;
    public const uint GL_OFFSET = 0x92FC;
    public const uint GL_BLOCK_INDEX = 0x92FD;
    public const uint GL_ARRAY_STRIDE = 0x92FE;
    public const uint GL_MATRIX_STRIDE = 0x92FF;
    public const uint GL_IS_ROW_MAJOR = 0x9300;
    public const uint GL_ATOMIC_COUNTER_BUFFER_INDEX = 0x9301;
    public const uint GL_BUFFER_BINDING = 0x9302;
    public const uint GL_BUFFER_DATA_SIZE = 0x9303;
    public const uint GL_NUM_ACTIVE_VARIABLES = 0x9304;
    public const uint GL_ACTIVE_VARIABLES = 0x9305;
    public const uint GL_REFERENCED_BY_VERTEX_SHADER = 0x9306;
    public const uint GL_REFERENCED_BY_FRAGMENT_SHADER = 0x930A;
    public const uint GL_REFERENCED_BY_COMPUTE_SHADER = 0x930B;
    public const uint GL_TOP_LEVEL_ARRAY_SIZE = 0x930C;
    public const uint GL_TOP_LEVEL_ARRAY_STRIDE = 0x930D;
    public const uint GL_LOCATION = 0x930E;
    public const uint GL_VERTEX_SHADER_BIT = 0x00000001;
    public const uint GL_FRAGMENT_SHADER_BIT = 0x00000002;
    public const uint GL_ALL_SHADER_BITS = 0xFFFFFFFF;
    public const uint GL_PROGRAM_SEPARABLE = 0x8258;
    public const uint GL_ACTIVE_PROGRAM = 0x8259;
    public const uint GL_PROGRAM_PIPELINE_BINDING = 0x825A;
    public const uint GL_ATOMIC_COUNTER_BUFFER_BINDING = 0x92C1;
    public const uint GL_ATOMIC_COUNTER_BUFFER_START = 0x92C2;
    public const uint GL_ATOMIC_COUNTER_BUFFER_SIZE = 0x92C3;
    public const uint GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS = 0x92CC;
    public const uint GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS = 0x92D0;
    public const uint GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS = 0x92D1;
    public const uint GL_MAX_VERTEX_ATOMIC_COUNTERS = 0x92D2;
    public const uint GL_MAX_FRAGMENT_ATOMIC_COUNTERS = 0x92D6;
    public const uint GL_MAX_COMBINED_ATOMIC_COUNTERS = 0x92D7;
    public const uint GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE = 0x92D8;
    public const uint GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS = 0x92DC;
    public const uint GL_ACTIVE_ATOMIC_COUNTER_BUFFERS = 0x92D9;
    public const uint GL_UNSIGNED_INT_ATOMIC_COUNTER = 0x92DB;
    public const uint GL_MAX_IMAGE_UNITS = 0x8F38;
    public const uint GL_MAX_VERTEX_IMAGE_UNIFORMS = 0x90CA;
    public const uint GL_MAX_FRAGMENT_IMAGE_UNIFORMS = 0x90CE;
    public const uint GL_MAX_COMBINED_IMAGE_UNIFORMS = 0x90CF;
    public const uint GL_IMAGE_BINDING_NAME = 0x8F3A;
    public const uint GL_IMAGE_BINDING_LEVEL = 0x8F3B;
    public const uint GL_IMAGE_BINDING_LAYERED = 0x8F3C;
    public const uint GL_IMAGE_BINDING_LAYER = 0x8F3D;
    public const uint GL_IMAGE_BINDING_ACCESS = 0x8F3E;
    public const uint GL_IMAGE_BINDING_FORMAT = 0x906E;
    public const uint GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT = 0x00000001;
    public const uint GL_ELEMENT_ARRAY_BARRIER_BIT = 0x00000002;
    public const uint GL_UNIFORM_BARRIER_BIT = 0x00000004;
    public const uint GL_TEXTURE_FETCH_BARRIER_BIT = 0x00000008;
    public const uint GL_SHADER_IMAGE_ACCESS_BARRIER_BIT = 0x00000020;
    public const uint GL_COMMAND_BARRIER_BIT = 0x00000040;
    public const uint GL_PIXEL_BUFFER_BARRIER_BIT = 0x00000080;
    public const uint GL_TEXTURE_UPDATE_BARRIER_BIT = 0x00000100;
    public const uint GL_BUFFER_UPDATE_BARRIER_BIT = 0x00000200;
    public const uint GL_FRAMEBUFFER_BARRIER_BIT = 0x00000400;
    public const uint GL_TRANSFORM_FEEDBACK_BARRIER_BIT = 0x00000800;
    public const uint GL_ATOMIC_COUNTER_BARRIER_BIT = 0x00001000;
    public const uint GL_ALL_BARRIER_BITS = 0xFFFFFFFF;
    public const uint GL_IMAGE_2D = 0x904D;
    public const uint GL_IMAGE_3D = 0x904E;
    public const uint GL_IMAGE_CUBE = 0x9050;
    public const uint GL_IMAGE_2D_ARRAY = 0x9053;
    public const uint GL_INT_IMAGE_2D = 0x9058;
    public const uint GL_INT_IMAGE_3D = 0x9059;
    public const uint GL_INT_IMAGE_CUBE = 0x905B;
    public const uint GL_INT_IMAGE_2D_ARRAY = 0x905E;
    public const uint GL_UNSIGNED_INT_IMAGE_2D = 0x9063;
    public const uint GL_UNSIGNED_INT_IMAGE_3D = 0x9064;
    public const uint GL_UNSIGNED_INT_IMAGE_CUBE = 0x9066;
    public const uint GL_UNSIGNED_INT_IMAGE_2D_ARRAY = 0x9069;
    public const uint GL_IMAGE_FORMAT_COMPATIBILITY_TYPE = 0x90C7;
    public const uint GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE = 0x90C8;
    public const uint GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS = 0x90C9;
    public const uint GL_READ_ONLY = 0x88B8;
    public const uint GL_WRITE_ONLY = 0x88B9;
    public const uint GL_READ_WRITE = 0x88BA;
    public const uint GL_SHADER_STORAGE_BUFFER = 0x90D2;
    public const uint GL_SHADER_STORAGE_BUFFER_BINDING = 0x90D3;
    public const uint GL_SHADER_STORAGE_BUFFER_START = 0x90D4;
    public const uint GL_SHADER_STORAGE_BUFFER_SIZE = 0x90D5;
    public const uint GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x90D6;
    public const uint GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x90DA;
    public const uint GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x90DB;
    public const uint GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 0x90DC;
    public const uint GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x90DD;
    public const uint GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 0x90DE;
    public const uint GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 0x90DF;
    public const uint GL_SHADER_STORAGE_BARRIER_BIT = 0x00002000;
    public const uint GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 0x8F39;
    public const uint GL_DEPTH_STENCIL_TEXTURE_MODE = 0x90EA;
    public const uint GL_STENCIL_INDEX = 0x1901;
    public const uint GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5E;
    public const uint GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5F;
    public const uint GL_SAMPLE_POSITION = 0x8E50;
    public const uint GL_SAMPLE_MASK = 0x8E51;
    public const uint GL_SAMPLE_MASK_VALUE = 0x8E52;
    public const uint GL_TEXTURE_2D_MULTISAMPLE = 0x9100;
    public const uint GL_MAX_SAMPLE_MASK_WORDS = 0x8E59;
    public const uint GL_MAX_COLOR_TEXTURE_SAMPLES = 0x910E;
    public const uint GL_MAX_DEPTH_TEXTURE_SAMPLES = 0x910F;
    public const uint GL_MAX_INTEGER_SAMPLES = 0x9110;
    public const uint GL_TEXTURE_BINDING_2D_MULTISAMPLE = 0x9104;
    public const uint GL_TEXTURE_SAMPLES = 0x9106;
    public const uint GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = 0x9107;
    public const uint GL_TEXTURE_WIDTH = 0x1000;
    public const uint GL_TEXTURE_HEIGHT = 0x1001;
    public const uint GL_TEXTURE_DEPTH = 0x8071;
    public const uint GL_TEXTURE_INTERNAL_FORMAT = 0x1003;
    public const uint GL_TEXTURE_RED_SIZE = 0x805C;
    public const uint GL_TEXTURE_GREEN_SIZE = 0x805D;
    public const uint GL_TEXTURE_BLUE_SIZE = 0x805E;
    public const uint GL_TEXTURE_ALPHA_SIZE = 0x805F;
    public const uint GL_TEXTURE_DEPTH_SIZE = 0x884A;
    public const uint GL_TEXTURE_STENCIL_SIZE = 0x88F1;
    public const uint GL_TEXTURE_SHARED_SIZE = 0x8C3F;
    public const uint GL_TEXTURE_RED_TYPE = 0x8C10;
    public const uint GL_TEXTURE_GREEN_TYPE = 0x8C11;
    public const uint GL_TEXTURE_BLUE_TYPE = 0x8C12;
    public const uint GL_TEXTURE_ALPHA_TYPE = 0x8C13;
    public const uint GL_TEXTURE_DEPTH_TYPE = 0x8C16;
    public const uint GL_TEXTURE_COMPRESSED = 0x86A1;
    public const uint GL_SAMPLER_2D_MULTISAMPLE = 0x9108;
    public const uint GL_INT_SAMPLER_2D_MULTISAMPLE = 0x9109;
    public const uint GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = 0x910A;
    public const uint GL_VERTEX_ATTRIB_BINDING = 0x82D4;
    public const uint GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D5;
    public const uint GL_VERTEX_BINDING_DIVISOR = 0x82D6;
    public const uint GL_VERTEX_BINDING_OFFSET = 0x82D7;
    public const uint GL_VERTEX_BINDING_STRIDE = 0x82D8;
    public const uint GL_VERTEX_BINDING_BUFFER = 0x8F4F;
    public const uint GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D9;
    public const uint GL_MAX_VERTEX_ATTRIB_BINDINGS = 0x82DA;
    public const uint GL_MAX_VERTEX_ATTRIB_STRIDE = 0x82E5;
    public const uint GL_ES_VERSION_3_2 = 1;
    public const uint GL_MULTISAMPLE_LINE_WIDTH_RANGE = 0x9381;
    public const uint GL_MULTISAMPLE_LINE_WIDTH_GRANULARITY = 0x9382;
    public const uint GL_MULTIPLY = 0x9294;
    public const uint GL_SCREEN = 0x9295;
    public const uint GL_OVERLAY = 0x9296;
    public const uint GL_DARKEN = 0x9297;
    public const uint GL_LIGHTEN = 0x9298;
    public const uint GL_COLORDODGE = 0x9299;
    public const uint GL_COLORBURN = 0x929A;
    public const uint GL_HARDLIGHT = 0x929B;
    public const uint GL_SOFTLIGHT = 0x929C;
    public const uint GL_DIFFERENCE = 0x929E;
    public const uint GL_EXCLUSION = 0x92A0;
    public const uint GL_HSL_HUE = 0x92AD;
    public const uint GL_HSL_SATURATION = 0x92AE;
    public const uint GL_HSL_COLOR = 0x92AF;
    public const uint GL_HSL_LUMINOSITY = 0x92B0;
    public const uint GL_DEBUG_OUTPUT_SYNCHRONOUS = 0x8242;
    public const uint GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH = 0x8243;
    public const uint GL_DEBUG_CALLBACK_FUNCTION = 0x8244;
    public const uint GL_DEBUG_CALLBACK_USER_PARAM = 0x8245;
    public const uint GL_DEBUG_SOURCE_API = 0x8246;
    public const uint GL_DEBUG_SOURCE_WINDOW_SYSTEM = 0x8247;
    public const uint GL_DEBUG_SOURCE_SHADER_COMPILER = 0x8248;
    public const uint GL_DEBUG_SOURCE_THIRD_PARTY = 0x8249;
    public const uint GL_DEBUG_SOURCE_APPLICATION = 0x824A;
    public const uint GL_DEBUG_SOURCE_OTHER = 0x824B;
    public const uint GL_DEBUG_TYPE_ERROR = 0x824C;
    public const uint GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 0x824D;
    public const uint GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR = 0x824E;
    public const uint GL_DEBUG_TYPE_PORTABILITY = 0x824F;
    public const uint GL_DEBUG_TYPE_PERFORMANCE = 0x8250;
    public const uint GL_DEBUG_TYPE_OTHER = 0x8251;
    public const uint GL_DEBUG_TYPE_MARKER = 0x8268;
    public const uint GL_DEBUG_TYPE_PUSH_GROUP = 0x8269;
    public const uint GL_DEBUG_TYPE_POP_GROUP = 0x826A;
    public const uint GL_DEBUG_SEVERITY_NOTIFICATION = 0x826B;
    public const uint GL_MAX_DEBUG_GROUP_STACK_DEPTH = 0x826C;
    public const uint GL_DEBUG_GROUP_STACK_DEPTH = 0x826D;
    public const uint GL_BUFFER = 0x82E0;
    public const uint GL_SHADER = 0x82E1;
    public const uint GL_PROGRAM = 0x82E2;
    public const uint GL_VERTEX_ARRAY = 0x8074;
    public const uint GL_QUERY = 0x82E3;
    public const uint GL_PROGRAM_PIPELINE = 0x82E4;
    public const uint GL_SAMPLER = 0x82E6;
    public const uint GL_MAX_LABEL_LENGTH = 0x82E8;
    public const uint GL_MAX_DEBUG_MESSAGE_LENGTH = 0x9143;
    public const uint GL_MAX_DEBUG_LOGGED_MESSAGES = 0x9144;
    public const uint GL_DEBUG_LOGGED_MESSAGES = 0x9145;
    public const uint GL_DEBUG_SEVERITY_HIGH = 0x9146;
    public const uint GL_DEBUG_SEVERITY_MEDIUM = 0x9147;
    public const uint GL_DEBUG_SEVERITY_LOW = 0x9148;
    public const uint GL_DEBUG_OUTPUT = 0x92E0;
    public const uint GL_CONTEXT_FLAG_DEBUG_BIT = 0x00000002;
    public const uint GL_STACK_OVERFLOW = 0x0503;
    public const uint GL_STACK_UNDERFLOW = 0x0504;
    public const uint GL_GEOMETRY_SHADER = 0x8DD9;
    public const uint GL_GEOMETRY_SHADER_BIT = 0x00000004;
    public const uint GL_GEOMETRY_VERTICES_OUT = 0x8916;
    public const uint GL_GEOMETRY_INPUT_TYPE = 0x8917;
    public const uint GL_GEOMETRY_OUTPUT_TYPE = 0x8918;
    public const uint GL_GEOMETRY_SHADER_INVOCATIONS = 0x887F;
    public const uint GL_LAYER_PROVOKING_VERTEX = 0x825E;
    public const uint GL_LINES_ADJACENCY = 0x000A;
    public const uint GL_LINE_STRIP_ADJACENCY = 0x000B;
    public const uint GL_TRIANGLES_ADJACENCY = 0x000C;
    public const uint GL_TRIANGLE_STRIP_ADJACENCY = 0x000D;
    public const uint GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = 0x8DDF;
    public const uint GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2C;
    public const uint GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = 0x8A32;
    public const uint GL_MAX_GEOMETRY_INPUT_COMPONENTS = 0x9123;
    public const uint GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = 0x9124;
    public const uint GL_MAX_GEOMETRY_OUTPUT_VERTICES = 0x8DE0;
    public const uint GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = 0x8DE1;
    public const uint GL_MAX_GEOMETRY_SHADER_INVOCATIONS = 0x8E5A;
    public const uint GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = 0x8C29;
    public const uint GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS = 0x92CF;
    public const uint GL_MAX_GEOMETRY_ATOMIC_COUNTERS = 0x92D5;
    public const uint GL_MAX_GEOMETRY_IMAGE_UNIFORMS = 0x90CD;
    public const uint GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 0x90D7;
    public const uint GL_FIRST_VERTEX_CONVENTION = 0x8E4D;
    public const uint GL_LAST_VERTEX_CONVENTION = 0x8E4E;
    public const uint GL_UNDEFINED_VERTEX = 0x8260;
    public const uint GL_PRIMITIVES_GENERATED = 0x8C87;
    public const uint GL_FRAMEBUFFER_DEFAULT_LAYERS = 0x9312;
    public const uint GL_MAX_FRAMEBUFFER_LAYERS = 0x9317;
    public const uint GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = 0x8DA8;
    public const uint GL_FRAMEBUFFER_ATTACHMENT_LAYERED = 0x8DA7;
    public const uint GL_REFERENCED_BY_GEOMETRY_SHADER = 0x9309;
    public const uint GL_PRIMITIVE_BOUNDING_BOX = 0x92BE;
    public const uint GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT = 0x00000004;
    public const uint GL_CONTEXT_FLAGS = 0x821E;
    public const uint GL_LOSE_CONTEXT_ON_RESET = 0x8252;
    public const uint GL_GUILTY_CONTEXT_RESET = 0x8253;
    public const uint GL_INNOCENT_CONTEXT_RESET = 0x8254;
    public const uint GL_UNKNOWN_CONTEXT_RESET = 0x8255;
    public const uint GL_RESET_NOTIFICATION_STRATEGY = 0x8256;
    public const uint GL_NO_RESET_NOTIFICATION = 0x8261;
    public const uint GL_CONTEXT_LOST = 0x0507;
    public const uint GL_SAMPLE_SHADING = 0x8C36;
    public const uint GL_MIN_SAMPLE_SHADING_VALUE = 0x8C37;
    public const uint GL_MIN_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5B;
    public const uint GL_MAX_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5C;
    public const uint GL_FRAGMENT_INTERPOLATION_OFFSET_BITS = 0x8E5D;
    public const uint GL_PATCHES = 0x000E;
    public const uint GL_PATCH_VERTICES = 0x8E72;
    public const uint GL_TESS_CONTROL_OUTPUT_VERTICES = 0x8E75;
    public const uint GL_TESS_GEN_MODE = 0x8E76;
    public const uint GL_TESS_GEN_SPACING = 0x8E77;
    public const uint GL_TESS_GEN_VERTEX_ORDER = 0x8E78;
    public const uint GL_TESS_GEN_POINT_MODE = 0x8E79;
    public const uint GL_ISOLINES = 0x8E7A;
    public const uint GL_QUADS = 0x0007;
    public const uint GL_FRACTIONAL_ODD = 0x8E7B;
    public const uint GL_FRACTIONAL_EVEN = 0x8E7C;
    public const uint GL_MAX_PATCH_VERTICES = 0x8E7D;
    public const uint GL_MAX_TESS_GEN_LEVEL = 0x8E7E;
    public const uint GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E7F;
    public const uint GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E80;
    public const uint GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS = 0x8E81;
    public const uint GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS = 0x8E82;
    public const uint GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS = 0x8E83;
    public const uint GL_MAX_TESS_PATCH_COMPONENTS = 0x8E84;
    public const uint GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS = 0x8E85;
    public const uint GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS = 0x8E86;
    public const uint GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS = 0x8E89;
    public const uint GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS = 0x8E8A;
    public const uint GL_MAX_TESS_CONTROL_INPUT_COMPONENTS = 0x886C;
    public const uint GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS = 0x886D;
    public const uint GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E1E;
    public const uint GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E1F;
    public const uint GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS = 0x92CD;
    public const uint GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS = 0x92CE;
    public const uint GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS = 0x92D3;
    public const uint GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS = 0x92D4;
    public const uint GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS = 0x90CB;
    public const uint GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS = 0x90CC;
    public const uint GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS = 0x90D8;
    public const uint GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 0x90D9;
    public const uint GL_PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED = 0x8221;
    public const uint GL_IS_PER_PATCH = 0x92E7;
    public const uint GL_REFERENCED_BY_TESS_CONTROL_SHADER = 0x9307;
    public const uint GL_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x9308;
    public const uint GL_TESS_CONTROL_SHADER = 0x8E88;
    public const uint GL_TESS_EVALUATION_SHADER = 0x8E87;
    public const uint GL_TESS_CONTROL_SHADER_BIT = 0x00000008;
    public const uint GL_TESS_EVALUATION_SHADER_BIT = 0x00000010;
    public const uint GL_TEXTURE_BORDER_COLOR = 0x1004;
    public const uint GL_CLAMP_TO_BORDER = 0x812D;
    public const uint GL_TEXTURE_BUFFER = 0x8C2A;
    public const uint GL_TEXTURE_BUFFER_BINDING = 0x8C2A;
    public const uint GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2B;
    public const uint GL_TEXTURE_BINDING_BUFFER = 0x8C2C;
    public const uint GL_TEXTURE_BUFFER_DATA_STORE_BINDING = 0x8C2D;
    public const uint GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT = 0x919F;
    public const uint GL_SAMPLER_BUFFER = 0x8DC2;
    public const uint GL_INT_SAMPLER_BUFFER = 0x8DD0;
    public const uint GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8DD8;
    public const uint GL_IMAGE_BUFFER = 0x9051;
    public const uint GL_INT_IMAGE_BUFFER = 0x905C;
    public const uint GL_UNSIGNED_INT_IMAGE_BUFFER = 0x9067;
    public const uint GL_TEXTURE_BUFFER_OFFSET = 0x919D;
    public const uint GL_TEXTURE_BUFFER_SIZE = 0x919E;
    public const uint GL_COMPRESSED_RGBA_ASTC_4x4 = 0x93B0;
    public const uint GL_COMPRESSED_RGBA_ASTC_5x4 = 0x93B1;
    public const uint GL_COMPRESSED_RGBA_ASTC_5x5 = 0x93B2;
    public const uint GL_COMPRESSED_RGBA_ASTC_6x5 = 0x93B3;
    public const uint GL_COMPRESSED_RGBA_ASTC_6x6 = 0x93B4;
    public const uint GL_COMPRESSED_RGBA_ASTC_8x5 = 0x93B5;
    public const uint GL_COMPRESSED_RGBA_ASTC_8x6 = 0x93B6;
    public const uint GL_COMPRESSED_RGBA_ASTC_8x8 = 0x93B7;
    public const uint GL_COMPRESSED_RGBA_ASTC_10x5 = 0x93B8;
    public const uint GL_COMPRESSED_RGBA_ASTC_10x6 = 0x93B9;
    public const uint GL_COMPRESSED_RGBA_ASTC_10x8 = 0x93BA;
    public const uint GL_COMPRESSED_RGBA_ASTC_10x10 = 0x93BB;
    public const uint GL_COMPRESSED_RGBA_ASTC_12x10 = 0x93BC;
    public const uint GL_COMPRESSED_RGBA_ASTC_12x12 = 0x93BD;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4 = 0x93D0;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4 = 0x93D1;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5 = 0x93D2;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5 = 0x93D3;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6 = 0x93D4;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5 = 0x93D5;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6 = 0x93D6;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8 = 0x93D7;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5 = 0x93D8;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6 = 0x93D9;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8 = 0x93DA;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10 = 0x93DB;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10 = 0x93DC;
    public const uint GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12 = 0x93DD;
    public const uint GL_TEXTURE_CUBE_MAP_ARRAY = 0x9009;
    public const uint GL_TEXTURE_BINDING_CUBE_MAP_ARRAY = 0x900A;
    public const uint GL_SAMPLER_CUBE_MAP_ARRAY = 0x900C;
    public const uint GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW = 0x900D;
    public const uint GL_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900E;
    public const uint GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900F;
    public const uint GL_IMAGE_CUBE_MAP_ARRAY = 0x9054;
    public const uint GL_INT_IMAGE_CUBE_MAP_ARRAY = 0x905F;
    public const uint GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY = 0x906A;
    public const uint GL_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9102;
    public const uint GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = 0x9105;
    public const uint GL_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910B;
    public const uint GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910C;
    public const uint GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910D;
    private static nint pfn_glActiveTexture;
    public static void glActiveTexture(uint texture) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glActiveTexture)(texture);
    
    private static nint pfn_glAttachShader;
    public static void glAttachShader(uint program, uint shader) => ((delegate* unmanaged[Stdcall]<uint, uint, void>)pfn_glAttachShader)(program, shader);
    
    private static nint pfn_glBindBuffer;
    public static void glBindBuffer(uint target, uint buffer) => ((delegate* unmanaged[Stdcall]<uint, uint, void>)pfn_glBindBuffer)(target, buffer);
    
    private static nint pfn_glBindFramebuffer;
    public static void glBindFramebuffer(uint target, uint framebuffer) => ((delegate* unmanaged[Stdcall]<uint, uint, void>)pfn_glBindFramebuffer)(target, framebuffer);
    
    private static nint pfn_glBindTexture;
    public static void glBindTexture(uint target, uint texture) => ((delegate* unmanaged[Stdcall]<uint, uint, void>)pfn_glBindTexture)(target, texture);
    
    private static nint pfn_glBlendFunc;
    public static void glBlendFunc(uint sfactor, uint dfactor) => ((delegate* unmanaged[Stdcall]<uint, uint, void>)pfn_glBlendFunc)(sfactor, dfactor);
    
    private static nint pfn_glBufferData;
    public static void glBufferData(uint target, int size, void* data, uint usage) => ((delegate* unmanaged[Stdcall]<uint, int, void*, uint, void>)pfn_glBufferData)(target, size, data, usage);
    
    private static nint pfn_glBufferSubData;
    public static void glBufferSubData(uint target, int offset, int size, void* data) => ((delegate* unmanaged[Stdcall]<uint, int, int, void*, void>)pfn_glBufferSubData)(target, offset, size, data);
    
    private static nint pfn_glCheckFramebufferStatus;
    public static uint glCheckFramebufferStatus(uint target) => ((delegate* unmanaged[Stdcall]<uint, uint>)pfn_glCheckFramebufferStatus)(target);
    
    private static nint pfn_glClear;
    public static void glClear(uint mask) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glClear)(mask);
    
    private static nint pfn_glClearColor;
    public static void glClearColor(float red, float green, float blue, float alpha) => ((delegate* unmanaged[Stdcall]<float, float, float, float, void>)pfn_glClearColor)(red, green, blue, alpha);
    
    private static nint pfn_glClearDepthf;
    public static void glClearDepthf(float d) => ((delegate* unmanaged[Stdcall]<float, void>)pfn_glClearDepthf)(d);
    
    private static nint pfn_glClearStencil;
    public static void glClearStencil(int s) => ((delegate* unmanaged[Stdcall]<int, void>)pfn_glClearStencil)(s);
    
    private static nint pfn_glCompileShader;
    public static void glCompileShader(uint shader) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glCompileShader)(shader);
    
    private static nint pfn_glCreateProgram;
    public static uint glCreateProgram() => ((delegate* unmanaged[Stdcall]<uint>)pfn_glCreateProgram)();
    
    private static nint pfn_glCreateShader;
    public static uint glCreateShader(uint type) => ((delegate* unmanaged[Stdcall]<uint, uint>)pfn_glCreateShader)(type);
    
    private static nint pfn_glCullFace;
    public static void glCullFace(uint mode) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glCullFace)(mode);
    
    private static nint pfn_glDeleteBuffers;
    public static void glDeleteBuffers(int n, uint* buffers) => ((delegate* unmanaged[Stdcall]<int, uint*, void>)pfn_glDeleteBuffers)(n, buffers);
    
    private static nint pfn_glDeleteFramebuffers;
    public static void glDeleteFramebuffers(int n, uint* framebuffers) => ((delegate* unmanaged[Stdcall]<int, uint*, void>)pfn_glDeleteFramebuffers)(n, framebuffers);
    
    private static nint pfn_glDeleteShader;
    public static void glDeleteShader(uint shader) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glDeleteShader)(shader);
    
    private static nint pfn_glDeleteTextures;
    public static void glDeleteTextures(int n, uint* textures) => ((delegate* unmanaged[Stdcall]<int, uint*, void>)pfn_glDeleteTextures)(n, textures);
    
    private static nint pfn_glDepthFunc;
    public static void glDepthFunc(uint func) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glDepthFunc)(func);
    
    private static nint pfn_glDepthMask;
    public static void glDepthMask(byte flag) => ((delegate* unmanaged[Stdcall]<byte, void>)pfn_glDepthMask)(flag);
    
    private static nint pfn_glDisable;
    public static void glDisable(uint cap) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glDisable)(cap);
    
    private static nint pfn_glDrawArrays;
    public static void glDrawArrays(uint mode, int first, int count) => ((delegate* unmanaged[Stdcall]<uint, int, int, void>)pfn_glDrawArrays)(mode, first, count);
    
    private static nint pfn_glDrawElements;
    public static void glDrawElements(uint mode, int count, uint type, void* indices) => ((delegate* unmanaged[Stdcall]<uint, int, uint, void*, void>)pfn_glDrawElements)(mode, count, type, indices);
    
    private static nint pfn_glEnable;
    public static void glEnable(uint cap) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glEnable)(cap);
    
    private static nint pfn_glEnableVertexAttribArray;
    public static void glEnableVertexAttribArray(uint index) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glEnableVertexAttribArray)(index);
    
    private static nint pfn_glFinish;
    public static void glFinish() => ((delegate* unmanaged[Stdcall]<void>)pfn_glFinish)();
    
    private static nint pfn_glFlush;
    public static void glFlush() => ((delegate* unmanaged[Stdcall]<void>)pfn_glFlush)();
    
    private static nint pfn_glFramebufferTexture2D;
    public static void glFramebufferTexture2D(uint target, uint attachment, uint textarget, uint texture, int level) => ((delegate* unmanaged[Stdcall]<uint, uint, uint, uint, int, void>)pfn_glFramebufferTexture2D)(target, attachment, textarget, texture, level);
    
    private static nint pfn_glGenBuffers;
    public static void glGenBuffers(int n, uint* buffers) => ((delegate* unmanaged[Stdcall]<int, uint*, void>)pfn_glGenBuffers)(n, buffers);
    
    private static nint pfn_glGenerateMipmap;
    public static void glGenerateMipmap(uint target) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glGenerateMipmap)(target);
    
    private static nint pfn_glGenFramebuffers;
    public static void glGenFramebuffers(int n, uint* framebuffers) => ((delegate* unmanaged[Stdcall]<int, uint*, void>)pfn_glGenFramebuffers)(n, framebuffers);
    
    private static nint pfn_glGenTextures;
    public static void glGenTextures(int n, uint* textures) => ((delegate* unmanaged[Stdcall]<int, uint*, void>)pfn_glGenTextures)(n, textures);
    
    private static nint pfn_glGetBufferParameteriv;
    public static void glGetBufferParameteriv(uint target, uint pname, int* @params) => ((delegate* unmanaged[Stdcall]<uint, uint, int*, void>)pfn_glGetBufferParameteriv)(target, pname, @params);
    
    private static nint pfn_glGetIntegerv;
    public static void glGetIntegerv(uint pname, int* data) => ((delegate* unmanaged[Stdcall]<uint, int*, void>)pfn_glGetIntegerv)(pname, data);
    
    private static nint pfn_glGetProgramiv;
    public static void glGetProgramiv(uint program, uint pname, int* @params) => ((delegate* unmanaged[Stdcall]<uint, uint, int*, void>)pfn_glGetProgramiv)(program, pname, @params);
    
    private static nint pfn_glGetProgramInfoLog;
    public static void glGetProgramInfoLog(uint program, int bufSize, int* length, byte* infoLog) => ((delegate* unmanaged[Stdcall]<uint, int, int*, byte*, void>)pfn_glGetProgramInfoLog)(program, bufSize, length, infoLog);
    
    private static nint pfn_glGetShaderiv;
    public static void glGetShaderiv(uint shader, uint pname, int* @params) => ((delegate* unmanaged[Stdcall]<uint, uint, int*, void>)pfn_glGetShaderiv)(shader, pname, @params);
    
    private static nint pfn_glGetShaderInfoLog;
    public static void glGetShaderInfoLog(uint shader, int bufSize, int* length, byte* infoLog) => ((delegate* unmanaged[Stdcall]<uint, int, int*, byte*, void>)pfn_glGetShaderInfoLog)(shader, bufSize, length, infoLog);
    
    private static nint pfn_glGetUniformLocation;
    public static int glGetUniformLocation(uint program, byte* name) => ((delegate* unmanaged[Stdcall]<uint, byte*, int>)pfn_glGetUniformLocation)(program, name);
    
    private static nint pfn_glLinkProgram;
    public static void glLinkProgram(uint program) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glLinkProgram)(program);
    
    private static nint pfn_glPixelStorei;
    public static void glPixelStorei(uint pname, int param) => ((delegate* unmanaged[Stdcall]<uint, int, void>)pfn_glPixelStorei)(pname, param);
    
    private static nint pfn_glReadPixels;
    public static void glReadPixels(int x, int y, int width, int height, uint format, uint type, void* pixels) => ((delegate* unmanaged[Stdcall]<int, int, int, int, uint, uint, void*, void>)pfn_glReadPixels)(x, y, width, height, format, type, pixels);
    
    private static nint pfn_glShaderSource;
    public static void glShaderSource(uint shader, int count, byte** @string, int* length) => ((delegate* unmanaged[Stdcall]<uint, int, byte**, int*, void>)pfn_glShaderSource)(shader, count, @string, length);
    
    private static nint pfn_glStencilFunc;
    public static void glStencilFunc(uint func, int @ref, uint mask) => ((delegate* unmanaged[Stdcall]<uint, int, uint, void>)pfn_glStencilFunc)(func, @ref, mask);
    
    private static nint pfn_glStencilMask;
    public static void glStencilMask(uint mask) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glStencilMask)(mask);
    
    private static nint pfn_glStencilOp;
    public static void glStencilOp(uint fail, uint zfail, uint zpass) => ((delegate* unmanaged[Stdcall]<uint, uint, uint, void>)pfn_glStencilOp)(fail, zfail, zpass);
    
    private static nint pfn_glTexImage2D;
    public static void glTexImage2D(uint target, int level, int internalformat, int width, int height, int border, uint format, uint type, void* pixels) => ((delegate* unmanaged[Stdcall]<uint, int, int, int, int, int, uint, uint, void*, void>)pfn_glTexImage2D)(target, level, internalformat, width, height, border, format, type, pixels);
    
    private static nint pfn_glTexParameteri;
    public static void glTexParameteri(uint target, uint pname, int param) => ((delegate* unmanaged[Stdcall]<uint, uint, int, void>)pfn_glTexParameteri)(target, pname, param);
    
    private static nint pfn_glTexSubImage2D;
    public static void glTexSubImage2D(uint target, int level, int xoffset, int yoffset, int width, int height, uint format, uint type, void* pixels) => ((delegate* unmanaged[Stdcall]<uint, int, int, int, int, int, uint, uint, void*, void>)pfn_glTexSubImage2D)(target, level, xoffset, yoffset, width, height, format, type, pixels);
    
    private static nint pfn_glUniform1f;
    public static void glUniform1f(int location, float v0) => ((delegate* unmanaged[Stdcall]<int, float, void>)pfn_glUniform1f)(location, v0);
    
    private static nint pfn_glUniform1fv;
    public static void glUniform1fv(int location, int count, float* value) => ((delegate* unmanaged[Stdcall]<int, int, float*, void>)pfn_glUniform1fv)(location, count, value);
    
    private static nint pfn_glUniform1i;
    public static void glUniform1i(int location, int v0) => ((delegate* unmanaged[Stdcall]<int, int, void>)pfn_glUniform1i)(location, v0);
    
    private static nint pfn_glUniform1iv;
    public static void glUniform1iv(int location, int count, int* value) => ((delegate* unmanaged[Stdcall]<int, int, int*, void>)pfn_glUniform1iv)(location, count, value);
    
    private static nint pfn_glUniform2fv;
    public static void glUniform2fv(int location, int count, float* value) => ((delegate* unmanaged[Stdcall]<int, int, float*, void>)pfn_glUniform2fv)(location, count, value);
    
    private static nint pfn_glUniform2iv;
    public static void glUniform2iv(int location, int count, int* value) => ((delegate* unmanaged[Stdcall]<int, int, int*, void>)pfn_glUniform2iv)(location, count, value);
    
    private static nint pfn_glUniform3fv;
    public static void glUniform3fv(int location, int count, float* value) => ((delegate* unmanaged[Stdcall]<int, int, float*, void>)pfn_glUniform3fv)(location, count, value);
    
    private static nint pfn_glUniform3iv;
    public static void glUniform3iv(int location, int count, int* value) => ((delegate* unmanaged[Stdcall]<int, int, int*, void>)pfn_glUniform3iv)(location, count, value);
    
    private static nint pfn_glUniform4f;
    public static void glUniform4f(int location, float v0, float v1, float v2, float v3) => ((delegate* unmanaged[Stdcall]<int, float, float, float, float, void>)pfn_glUniform4f)(location, v0, v1, v2, v3);
    
    private static nint pfn_glUniform4fv;
    public static void glUniform4fv(int location, int count, float* value) => ((delegate* unmanaged[Stdcall]<int, int, float*, void>)pfn_glUniform4fv)(location, count, value);
    
    private static nint pfn_glUniform4iv;
    public static void glUniform4iv(int location, int count, int* value) => ((delegate* unmanaged[Stdcall]<int, int, int*, void>)pfn_glUniform4iv)(location, count, value);
    
    private static nint pfn_glUniformMatrix4fv;
    public static void glUniformMatrix4fv(int location, int count, byte transpose, float* value) => ((delegate* unmanaged[Stdcall]<int, int, byte, float*, void>)pfn_glUniformMatrix4fv)(location, count, transpose, value);
    
    private static nint pfn_glUseProgram;
    public static void glUseProgram(uint program) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glUseProgram)(program);
    
    private static nint pfn_glVertexAttribPointer;
    public static void glVertexAttribPointer(uint index, int size, uint type, byte normalized, int stride, void* pointer) => ((delegate* unmanaged[Stdcall]<uint, int, uint, byte, int, void*, void>)pfn_glVertexAttribPointer)(index, size, type, normalized, stride, pointer);
    
    private static nint pfn_glViewport;
    public static void glViewport(int x, int y, int width, int height) => ((delegate* unmanaged[Stdcall]<int, int, int, int, void>)pfn_glViewport)(x, y, width, height);
    
    private static nint pfn_glUnmapBuffer;
    public static byte glUnmapBuffer(uint target) => ((delegate* unmanaged[Stdcall]<uint, byte>)pfn_glUnmapBuffer)(target);
    
    private static nint pfn_glUniformMatrix3x2fv;
    public static void glUniformMatrix3x2fv(int location, int count, byte transpose, float* value) => ((delegate* unmanaged[Stdcall]<int, int, byte, float*, void>)pfn_glUniformMatrix3x2fv)(location, count, transpose, value);
    
    private static nint pfn_glBlitFramebuffer;
    public static void glBlitFramebuffer(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, uint mask, uint filter) => ((delegate* unmanaged[Stdcall]<int, int, int, int, int, int, int, int, uint, uint, void>)pfn_glBlitFramebuffer)(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter);
    
    private static nint pfn_glMapBufferRange;
    public static void* glMapBufferRange(uint target, int offset, int length, uint access) => ((delegate* unmanaged[Stdcall]<uint, int, int, uint, void*>)pfn_glMapBufferRange)(target, offset, length, access);
    
    private static nint pfn_glBindVertexArray;
    public static void glBindVertexArray(uint array) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glBindVertexArray)(array);
    
    private static nint pfn_glDeleteVertexArrays;
    public static void glDeleteVertexArrays(int n, uint* arrays) => ((delegate* unmanaged[Stdcall]<int, uint*, void>)pfn_glDeleteVertexArrays)(n, arrays);
    
    private static nint pfn_glGenVertexArrays;
    public static void glGenVertexArrays(int n, uint* arrays) => ((delegate* unmanaged[Stdcall]<int, uint*, void>)pfn_glGenVertexArrays)(n, arrays);
    
    private static nint pfn_glBindBufferBase;
    public static void glBindBufferBase(uint target, uint index, uint buffer) => ((delegate* unmanaged[Stdcall]<uint, uint, uint, void>)pfn_glBindBufferBase)(target, index, buffer);
    
    private static nint pfn_glUniform1ui;
    public static void glUniform1ui(int location, uint v0) => ((delegate* unmanaged[Stdcall]<int, uint, void>)pfn_glUniform1ui)(location, v0);
    
    private static nint pfn_glUniform3ui;
    public static void glUniform3ui(int location, uint v0, uint v1, uint v2) => ((delegate* unmanaged[Stdcall]<int, uint, uint, uint, void>)pfn_glUniform3ui)(location, v0, v1, v2);
    
    private static nint pfn_glDrawArraysInstanced;
    public static void glDrawArraysInstanced(uint mode, int first, int count, int instancecount) => ((delegate* unmanaged[Stdcall]<uint, int, int, int, void>)pfn_glDrawArraysInstanced)(mode, first, count, instancecount);
    
    private static nint pfn_glDrawElementsInstanced;
    public static void glDrawElementsInstanced(uint mode, int count, uint type, void* indices, int instancecount) => ((delegate* unmanaged[Stdcall]<uint, int, uint, void*, int, void>)pfn_glDrawElementsInstanced)(mode, count, type, indices, instancecount);
    
    private static nint pfn_glVertexAttribDivisor;
    public static void glVertexAttribDivisor(uint index, uint divisor) => ((delegate* unmanaged[Stdcall]<uint, uint, void>)pfn_glVertexAttribDivisor)(index, divisor);
    
    private static nint pfn_glDispatchCompute;
    public static void glDispatchCompute(uint num_groups_x, uint num_groups_y, uint num_groups_z) => ((delegate* unmanaged[Stdcall]<uint, uint, uint, void>)pfn_glDispatchCompute)(num_groups_x, num_groups_y, num_groups_z);
    
    private static nint pfn_glGetProgramResourceIndex;
    public static uint glGetProgramResourceIndex(uint program, uint programInterface, byte* name) => ((delegate* unmanaged[Stdcall]<uint, uint, byte*, uint>)pfn_glGetProgramResourceIndex)(program, programInterface, name);
    
    private static nint pfn_glGetProgramResourceiv;
    public static void glGetProgramResourceiv(uint program, uint programInterface, uint index, int propCount, uint* props, int bufSize, int* length, int* @params) => ((delegate* unmanaged[Stdcall]<uint, uint, uint, int, uint*, int, int*, int*, void>)pfn_glGetProgramResourceiv)(program, programInterface, index, propCount, props, bufSize, length, @params);
    
    private static nint pfn_glMemoryBarrier;
    public static void glMemoryBarrier(uint barriers) => ((delegate* unmanaged[Stdcall]<uint, void>)pfn_glMemoryBarrier)(barriers);
    
    private static nint pfn_glDebugMessageCallback;
    public static void glDebugMessageCallback(delegate* unmanaged[Stdcall]<uint, uint, uint, uint, int, byte*, void*, void> callback, void* userParam) => ((delegate* unmanaged[Stdcall]<delegate* unmanaged[Stdcall]<uint, uint, uint, uint, int, byte*, void*, void>, void*, void>)pfn_glDebugMessageCallback)(callback, userParam);
    
    private static nint pfn_glFramebufferTexture;
    public static void glFramebufferTexture(uint target, uint attachment, uint texture, int level) => ((delegate* unmanaged[Stdcall]<uint, uint, uint, int, void>)pfn_glFramebufferTexture)(target, attachment, texture, level);
    
}
